/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_criteo_recommendation_knn_KnnServiceLib */

#ifndef _Included_com_criteo_recommendation_knn_KnnServiceLib
#define _Included_com_criteo_recommendation_knn_KnnServiceLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_criteo_recommendation_knn_KnnServiceLib
 * Method:    createAngular
 * Signature: (II)J
 */
JNIEXPORT void JNICALL Java_com_criteo_recommendation_knn_KnnServiceLib_nativeInit
        (JNIEnv *, jclass);

JNIEXPORT jlong JNICALL Java_com_criteo_recommendation_knn_KnnServiceLib_createAngular
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_criteo_recommendation_knn_KnnServiceLib
 * Method:    createEuclidean
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_criteo_recommendation_knn_KnnServiceLib_createEuclidean
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_criteo_recommendation_knn_KnnServiceLib
 * Method:    createInnerProduct
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_criteo_recommendation_knn_KnnServiceLib_createInnerProduct
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_criteo_recommendation_knn_KnnServiceLib
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_criteo_recommendation_knn_KnnServiceLib_destroy
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_criteo_recommendation_knn_KnnServiceLib
 * Method:    loadIndex
 * Signature: (JILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_criteo_recommendation_knn_KnnServiceLib_loadIndex
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     com_criteo_recommendation_knn_KnnServiceLib
 * Method:    addIndices
 * Signature: (J[I[J)V
 */
JNIEXPORT void JNICALL Java_com_criteo_recommendation_knn_KnnServiceLib_addIndices
  (JNIEnv *, jclass, jlong, jintArray, jlongArray);

/*
 * Class:     com_criteo_recommendation_knn_KnnServiceLib
 * Method:    getClosestItemsAvg
 * Signature: (J[I[J[J[IIJFI)Lcom/criteo/recommendation/knn/KnnResult;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_recommendation_knn_KnnServiceLib_getClosestItemsAvg
  (JNIEnv *, jclass, jlong, jintArray, jlongArray, jlongArray, jintArray, jint, jlong, jfloat, jint);

/*
 * Class:     com_criteo_recommendation_knn_KnnServiceLib
 * Method:    getItemsWeightedAvg
 * Signature: (J[I[J[J[IFI)[F
 */
JNIEXPORT jobject JNICALL Java_com_criteo_recommendation_knn_KnnServiceLib_getItemsWeightedAvg
  (JNIEnv *, jclass, jlong, jintArray, jlongArray, jlongArray, jintArray, jfloat, jint);

/*
 * Class:     com_criteo_recommendation_knn_KnnServiceLib
 * Method:    getIndicesIds
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_criteo_recommendation_knn_KnnServiceLib_getIndicesIds
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_criteo_recommendation_knn_KnnServiceLib
 * Method:    addNonSearchableItems
 * Signature: (JI[J[[F)V
 */
JNIEXPORT void JNICALL Java_com_criteo_recommendation_knn_KnnServiceLib_addNonSearchableItems
  (JNIEnv *, jclass, jlong, jint, jlongArray, jobjectArray);

/*
 * Class:     com_criteo_recommendation_knn_KnnServiceLib
 * Method:    fetchItem
 * Signature: (JIJ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_criteo_recommendation_knn_KnnServiceLib_fetchItem
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     com_criteo_recommendation_knn_KnnServiceLib
 * Method:    getNbExtraItems
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_criteo_recommendation_knn_KnnServiceLib_getNbExtraItems
  (JNIEnv *, jclass, jlong);

#pragma GCC diagnostic ignored "-Wwrite-strings"

/*
More info: https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/types.html
+----------------------------+-----------------------+
|      Type Signature        |       Java Type       |
+----------------------------+-----------------------+
| Z                          | boolean               |
| B                          | byte                  |
| C                          | char                  |
| S                          | short                 |
| I                          | int                   |
| J                          | long                  |
| F                          | float                 |
| D                          | double                |
| L fully-qualified-class ;  | fully-qualified-class |
| [ type                     | type[]                |
| ( arg-types ) ret-type     | method type           |
+----------------------------+-----------------------+
 */

static JNINativeMethod methods[] = {
        {"createAngular",         "(II)J",                                             (void *) Java_com_criteo_recommendation_knn_KnnServiceLib_createAngular},
        {"createEuclidean",       "(II)J",                                             (void *) Java_com_criteo_recommendation_knn_KnnServiceLib_createEuclidean},
        {"createInnerProduct",    "(II)J",                                             (void *) Java_com_criteo_recommendation_knn_KnnServiceLib_createInnerProduct},
        {"destroy",               "(J)V",                                              (void *) Java_com_criteo_recommendation_knn_KnnServiceLib_destroy},
        {"loadIndex",             "(JILjava/lang/String;)J",                           (void *) Java_com_criteo_recommendation_knn_KnnServiceLib_loadIndex},
        {"addIndices",            "(J[I[J)V",                                          (void *) Java_com_criteo_recommendation_knn_KnnServiceLib_addIndices},
        {"getClosestItemsAvg",    "(J[I[J[J[IIJFI)Lcom/criteo/recommendation/knn/KnnResult;", (void *) Java_com_criteo_recommendation_knn_KnnServiceLib_getClosestItemsAvg},
        {"getItemsWeightedAvg",   "(J[I[J[J[IFI)Lcom/criteo/recommendation/knn/UserEmbedding;", (void *) Java_com_criteo_recommendation_knn_KnnServiceLib_getItemsWeightedAvg},
        {"getIndicesIds",         "(J)[I",                                              (void *) Java_com_criteo_recommendation_knn_KnnServiceLib_getIndicesIds},
        {"addNonSearchableItems", "(JI[J[[F)V",                                         (void *) Java_com_criteo_recommendation_knn_KnnServiceLib_addNonSearchableItems},
        {"fetchItem",             "(JIJ)[F",                                            (void *) Java_com_criteo_recommendation_knn_KnnServiceLib_fetchItem},
        {"getNbExtraItems",       "(J)J",                                               (void *) Java_com_criteo_recommendation_knn_KnnServiceLib_getNbExtraItems}
};

#ifdef __cplusplus
}
#endif
#endif
